version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: start_dev
    restart: always
    volumes:
      - ./:/app
    networks:
      default: {}

networks:
  default:
    name: ${NETWORK_NAME:-nftgal-local}
    external: true
